### ISSUE TITLE
Run ESCM in debug mode

### ISSUE THREAD

**Issue by StavrevaS** [servicecatalog/crowbar-openstack#18]
The data bag of the proposal has already "debug" option for the barclamp.
Use this also for configuring debugging for ESCM (setup, tomee...)

**Comment by shimizuf** [comment]
There are two tasks here:

1. Ensure that the setup scripts `heat-config` and `deploy-escmserver` respect the debug setting and provide detailed logs if set
2. Ensure that the application respects the debug setting. To accomplish that, the debug setting must be passed through to the Docker Compose files so that the Docker variable TOMEE_DEBUG is set accordingly

**Comment by GoebelL** [comment]
This issue was moved to servicecatalog/crowbar-escm#18
